---
- name: restart gd-fuse
  block:
    - name: Reload services
      systemd:
        daemon_reload: true
    - name: Restart service
      systemd:
        name: google-drive-ocamlfuse
        state: restarted
        enabled: true
  become: true
